config/routes.rb
TenEvents::Application.routes.draw do
  
   root :to => 'site#index'
   
   namespace :admin do
     
    resources :users
    get "admin_pages/A_Summary"
    
   end
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/admin',  :to => 'admin#index'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/sessions', :to => 'sessions#create'

end

app/models/user.rb
class User < ActiveRecord::Base
	
	attr_accessor :password, :admin_public_bool
	attr_accessible :name, :email, :password, :password_confirmation, :admin_public_bool
	
	validates :name,	:presence => true,
						:uniqueness => true
						
	validates :email,	:presence => true,
						:uniqueness => true
	
	validates :password, :presence => true,
							:confirmation => true,
							:length => { :within => 6..40 }
							
	before_save :encrypt_password, :set_admin
	
	def has_password?(submitted_password)
	  encrypted_password == encrypt(submitted_password)
	end
	
	def self.authenticate(name, submitted_password)
      user = find_by_name(name)
      return nil  if user.nil?
      return user if user.has_password?(submitted_password)
	end
	
	def self.authenticate_with_salt(id, cookie_salt)
	  user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
	end

	
	private
	
	def set_admin
	  
	  logger.debug(self.admin_public_bool.to_s)
	  
	 if self.admin_public_bool == 1
	   self.admin = true
	   logger.debug"bool == 1"
   else
     self.admin = nil
     logger.debug"bool == 0"
   end
  end
	
		def encrypt_password
		  self.salt = make_salt if new_record?
		  self.encrypted_password = encrypt(password)
		end
		
		def encrypt(string)
		  secure_hash("#{salt}--#{string}")
		end
		
		def make_salt
		  secure_hash("#{Time.now.utc}--#{password}")
		end
		
		def secure_hash(string)
		  Digest::SHA2.hexdigest(string)
		end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  
  before_filter :authenticate_admin
  #before_filter :authenticate_public
  
def index
  logger.debug"definitely in the admin controller for users...."
  @users = User.all
  
end
  
  def new
	@user = User.new
	@title = "Create New User"
	
	logger.debug"definitely in the admin controller for new users...."
	
	respond_to do |format|
      format.html { render 'new' }
      format.xml  { render :xml => @user }
	end
  
  end
  
  def show
    @user = User.find(params[:id])
	@title = @user.name
  end
  
  def create
 
 #This is in the public users controller
 
  end
  
  def edit
    
    @user = User.find(params[:id])
    @title = @user.name
    
  end
  
  def update

    #This is in the public users controller
	
  end

def destroy
  
  logger.debug"definitely in the admin controller for destroy users...."
  
  User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to admin_users_path
  
  
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  include SessionsHelper
  
  #THIS IS THE PUBLIC USERS CONTROLLER!!!
  
  before_filter :authenticate_public, :except => [:new, :create]
  
def index
  
  @users = User.all
  
end
  
  def new
	@user = User.new
	@title = "Create New User"
	
	respond_to do |format|
      format.html { render 'new' }
      format.xml  { render :xml => @user }
	end
  
  end
  
  def show
    @user = User.find(params[:id])
	  @title = @user.name
  end
  
  def create
    @user = User.new(params[:user])
    
    logger.debug "in create from public users"
	
	respond_to do |format|
     
     if @user.save
       
       unless signed_in?
        sign_in @user
       end
       
       if admin_user?
         logger.debug"just saved, trying to redirect"
   	     format.html { redirect_to admin_users_path, :flash => { :success => "User created" }}
   	     format.xml  { render :xml => admin_users_path, :status => :created, :location => @user }
       else
	       format.html { redirect_to root_path, :flash => { :success => "Thanks for signing up!" }}
	       format.xml  { render :xml => root_path, :status => :created, :location => @user }
       end
	    
     else
      @title = "Sign up"
	    format.html { render 'new' }
	    format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
     end
	 end
  end
  
  def edit
    
    @user = User.find(params[:id])
    @title = @user.name
    
  end
  
  def update
    @user = User.find(params[:id])
	
    if @user.update_attributes(params[:user])
	
	    if admin_user?
        flash[:success] = "User updated."
        redirect_to admin_users_path
      else
        flash[:success] = "User updated."
        redirect_to users_path
      end
    else
      @title = @user.name
      render 'edit'
    end
  end

def destroy
  
  logger.debug "in destroy from public users"
  
  User.find(params[:id]).destroy
    
    if admin_user?
      flash[:success] = "User destroyed."
      redirect_to admin_users_path
    else
      flash[:success] = "User destroyed."
      redirect_to users_path
    end
  
end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<!-- admin users form -->
<%= form_for(@user) do |f| %>

<%= render 'shared/error_messages', :object => f.object %>

 <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

 <div class="field">
    <%= f.label "Admin user?" %><br />
    <%= f.check_box :admin_public_bool %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/admin/users/_table.html.erb
<!-- admin users table -->
<table>
  <tr>
    <th>Name </th>
    <th>Email </th>
    <th>Admin </th>
  </tr>
<% @users.each do |user| %>
    
	<td><%= user.name%></td>
    <td><%= user.email %></td>
	<% if user.admin %> <td> yes </td> 
		<% else %> <td> no </td>
	<% end %>
	<td><%= link_to 'Show', user %></td>
	<td><%= link_to "Edit", edit_admin_user_path(user) %></td>
   	<td><%= link_to "Delete", user, :method => :delete, :confirm => 'Are you sure?',  
									 :title => "Delete User" %></td>
  </tr>
<% end %>
</table>

app/views/admin/users/edit.html.erb
<h1><%= @user.name %></h1>

<%= render 'form'%>

app/views/admin/users/index.html.erb
<h1> All Other Users </h1>

<li><%= link_to "New User", new_admin_user_path %></li>

<%= render 'table' %>

app/views/admin/users/new.html.erb
<h1>New User</h1>
<p> Thanks for joining, please fill out the form to sign up </p>
 
 <%= render 'form'%>

app/views/admin/users/show.html.erb
<h1>
  <%= @user.name %>
</h1>


<%= @user.name %>, <%= @user.email %>