config/routes.rb
TenEvents::Application.routes.draw do
  
   root :to => 'site#index'
   
   namespace :admin do
     
    resources :users
    get "admin_pages/A_Summary"
    
   end
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/admin',  :to => 'admin#index'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/sessions', :to => 'sessions#create'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><a href="#">Link</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
 <% logo = image_tag("logo_transparent.png", :alt => "Ten Events", :class => "round") %>
  <%= link_to logo, root_path %>
   <nav class="round">
    <ul>
	<% if !signed_in? %>
	<li><%= link_to "Log in", signin_path %></li>
	<li><%= link_to "New Member", new_user_path %></li>
	<% else %>
	
   		<% if !admin_user? %>
   		  <li><%= link_to "Summary", root_path %></li>
   		  <li><%= link_to "Users", users_path %></li>
   		  <% if signed_in? %>
   		  <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
   		  <% end %>
   		<% end %>
   		
   		<% if admin_user? %>
   		  <li><%= link_to "Admin Summary", admin_path %></li>
   		  <li><%= link_to "Users", admin_users_path %></li>
   		  <% if signed_in? %>
   		  <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
   		  <% end %>
   		<% end %>
	<% end %>
	
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
	<%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>

</head>
	<body>
	  <div class="container">
		
		<%= render 'layouts/header' %>
			  
		<section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
			  
				<%= yield %>
		      </section>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	  </div>

</body>
</html>